### ISSUE TITLE
nginx-ui-base image 可能需要musl?

### ISSUE THREAD

**Issue by nthsky** [0xJacky/uozi-docker#1]
自己构建nginx-ui，采用docker多阶段构建，步骤如下：
1. 前端构建没问题，忽略
2. 编译在golang:1.22.1-alpine3.19镜像中执行，因为sqlite初始化需要cgo，首先安装编译需要的环境gcc，再进行编译
``shell
apk add build-base
CGO_ENABLED=1 go build -tags=jsoniter -ldflags "-X 'github.com/0xJacky/Nginx-UI/server/settings.buildTime=$(date +%s)'" -o dist/nginx-ui -v main.go
``
3. 最后使用uozi/nginx-ui-base:latest镜像运行，会报如下错误：
``cannot execute: required file not found``
4. ldd查看nginx-ui依赖，发现缺少musl
``libc.musl-x86_64.so.1 => not found``
5. apt install musl后解决

能否说一下你的构建步骤，我这个步骤基础镜像必须要额外添加musl

**Comment by 0xJacky** [comment]
我是先在 Github Actions 用 musl 的静态编译 go，然后拷贝可执行文件到容器镜像里

**Comment by 0xJacky** [comment]
所以 base image 不需要 musl 的环境了

**Comment by nthsky** [comment]
ok，了解了
